apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: car-service
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - image: quay.io/ruben/reservations-service:latest
---
apiVersion: eventing.knative.dev/v1beta1
kind: Trigger
metadata:
  annotations:
    knative-eventing-injection: enabled
  name: car-reservations
spec:
  broker: default
  filter:
    attributes:
      type: CarReservation
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: car-service
---
apiVersion: eventing.knative.dev/v1beta1
kind: Trigger
metadata:
  annotations:
    knative-eventing-injection: enabled
  name: car-reservations-cancel
spec:
  broker: default
  filter:
    attributes:
      type: CarReservationCancel
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: car-service