apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: car-service
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - image: quay.io/ruben/reservations-service:jvm-latest
          env:
            - name: LRA_HTTP_HOST
              value: lra-coordinator
            - name: LRA_HTTP_PORT
              value: "8080"
---
apiVersion: eventing.knative.dev/v1beta1
kind: Trigger
metadata:
  name: car-reservations
spec:
  broker: default
  filter:
    attributes:
      type: CarReservationRequest
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: car-service
---
apiVersion: eventing.knative.dev/v1beta1
kind: Trigger
metadata:
  name: car-reservations-cancel
spec:
  broker: default
  filter:
    attributes:
      type: CancelCarReservation
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: car-service