apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: stock-service
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - image: quay.io/ruben/reservations-service:jvm-latest
          env:
            - name: LRA_HTTP_HOST
              value: lra-coordinator
            - name: LRA_HTTP_PORT
              value: "8080"
---
apiVersion: eventing.knative.dev/v1beta1
kind: Trigger
metadata:
  name: stock-reserve
spec:
  broker: default
  filter:
    attributes:
      type: ReserveStock
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: stock-service
---
apiVersion: eventing.knative.dev/v1beta1
kind: Trigger
metadata:
  name: stock-cancel
spec:
  broker: default
  filter:
    attributes:
      type: CancelStock
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: stock-service